name: stoop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.2
  animated_text_kit: ^4.2.2
  get: ^4.6.5
  flutter_svg: ^2.0.5
  animations: ^2.0.8
  animate_do: ^3.0.2
  font_awesome_flutter: ^10.4.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  web_socket_channel: ^2.4.0
  http: ^0.13.6
  selection_menu: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logo.png
    - assets/images/travel_easy.png

fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen-Bold.ttf
        - asset: fonts/Sen-ExtraBold.ttf
        - asset: fonts/Sen-Medium.ttf
        - asset: fonts/Sen-Regular.ttf
        - asset: fonts/Sen-SemiBold.ttf
        - asset: fonts/Sen-VariableFont_wght.ttf
